pool:
  vmImage: 'macOS 10.13'

steps:
- task: Xcode@5
  displayName: 'Build the app using Xcode'
  inputs:
    actions: 'clean build'
    sdk: 'iphoneos'
    scheme: 'HelloiOS'
    configuration: 'Debug'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    useXcpretty: 'false'



